### ISSUE TITLE
Case sensitive !

### ISSUE THREAD

**Issue by kiroxas** [olegskl/invasive-kanji#3]
The answers seems to be case sensitive ! Fix that !

**Comment by olegskl** [comment]
![nomeme](https://f.cloud.github.com/assets/298275/40633/5734966a-55ad-11e2-8573-28955662915b.JPG)

**Comment by kiroxas** [comment]
![32837376](https://f.cloud.github.com/assets/3176062/40631/363b1a92-55ad-11e2-94c8-2fbacec2a2fa.jpg)
